INSERT INTO cooks (user_id, storage_id) VALUES (2, 1);
INSERT INTO cooks (user_id, storage_id) VALUES (1, 1);
INSERT INTO cooks (user_id, storage_id) VALUES (3, 1);
INSERT INTO cooks (user_id, storage_id) VALUES (17, 1);
INSERT INTO cooks (user_id, storage_id) VALUES (18, 1);
INSERT INTO cooks (user_id, storage_id) VALUES (19, 1);
INSERT INTO cooks (user_id, storage_id) VALUES (20, 1);
INSERT INTO cooks (user_id, storage_id) VALUES (21, 1);
INSERT INTO cooks (user_id, storage_id) VALUES (28, 1);