INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (2, 'Сергій', 'rand@app.com', 'СJBD0TYTu8QA', '+380996358122', '["storage", "operator", "reviews", "stats"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (3, 'Степан', 'Stepan@young-cafe.pp.ua', 'СJBD0TYTu8QA', '+380984521657', '["cook"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (4, 'Вітя', 'Vitya@young-cafe.pp.ua', 'В1s5TfwQ6106', '+380968546532', '["driver"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (6, 'Тарас', 'Taras.Fomin@gmail.com', 'Тuy9Lo2kcXD.', '+380987450593', '["user", "operator", "reviews", "storage", "stats"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (7, 'Віктор Іванович', 'describe@shot.com', 'Вugy9e4ib3CU', '+380237471947', '["user"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (8, 'Ігор Сергійович', 'secret@material.com', 'ІMERAeecflkU', '+380300005499', '["user"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (9, 'Іван Васильович', 'modern.island@struck.com', 'ІMERAeecflkU', '+380914538015', '["user"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (10, 'Максим Віталійович', 'finally.whole@harbor.com', 'МJWejvzJtIDo', '+380259619761', '["user"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (11, 'Олександр Святославович', 'book@brick.com', 'ОGW6Nf8hycGk', '+380354728602', '["user"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (12, 'Водій Іван', 'coach.difficulty@official.com', 'Вugy9e4ib3CU', '+380612327504', '["user", "driver"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (13, 'Водій Ігор', 'interior@run.com', 'Вugy9e4ib3CU', '+380702248037', '["user", "driver"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (14, 'Водій Василь', 'addition.silly@basis.com', 'Вugy9e4ib3CU', '+380343030580', '["user", "driver"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (15, 'Водій Микола', 'receive@under.com', 'Вugy9e4ib3CU', '+380639000831', '["user", "driver"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (16, 'Водій Віталій', 'improve@pet.com', 'Вugy9e4ib3CU', '+380137665964', '["user", "driver"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (17, 'Шеф Давид', 'season.connected@refer.com', 'ШzvKgCtLQQiY', '+380050613968', '["cook"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (18, 'Кухар Данил', 'beautiful@interest.com', 'КmDDkuFl8gWA', '+380725732743', '["cook"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (19, 'Кухар Василь', 'live@dream.com', 'КmDDkuFl8gWA', '+380786729710', '["cook"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (20, 'Кухар Катерина', 'doing@happen.com', 'КmDDkuFl8gWA', '+380690733080', '["cook"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (21, 'Кухар Іванна', 'those.sight@moment.com', 'КmDDkuFl8gWA', '+380900630247', '["cook"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (22, 'adminInstall', 'email@app.com', 'adC0FB/MyoPF.', '+38099635811', '["user", "operator", "reviews", "storage", "stats"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (23, 'Imya', 'email@email.com', 'ImkHVmD1xvDuo', '+38098847534', '["user", "operator", "reviews", "storage", "stats"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (24, 'apptest', 'emaill@email.com', 'ap32E97njsuDY', '+38098847532', '["user", "operator", "reviews", "storage", "stats"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (25, 'installMe', 'em@em.com', 'in3Fn4na3wVm.', '+38099923232', '["user", "operator", "reviews", "storage", "stats"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (26, 'Rffddc', 'Sfff@dxg.com', 'RfqmU2pzFCUoQ', '+3809659995', '["user", "operator", "reviews", "storage", "stats"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (27, 'ImyaRand', 'irasfsdf@gmail.com', 'ImkHVmD1xvDuo', '+38099231231', '["user", "operator", "reviews", "storage", "stats"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (28, 'Test', null, 'Te4jFl43vAtZc', null, '["driver", "storage", "operator", "reviews", "cook", "stats"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (29, 'User', null, 'UsGbkdStjNmsA', null, '["user"]', null);
INSERT INTO users (id, username, email, password, phone, roles, avatar) VALUES (30, 'Максим', 'painstyle01@gmail.com', 'МQutt44S3EzY', '+380635495005', '["storage", "operator", "reviews", "stats"]', null);