INSERT INTO ingredients (id, title, unit, floating, price) VALUES (1, 'Картопля', 'кг', 1, 500);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (2, 'Олія', 'л', 1, 1600);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (3, 'Оцет', 'л', 1, 2300);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (4, 'Кетчуп', 'кг', 1, 20000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (5, 'Оливки', '', 0, 100);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (6, 'Помідори', 'кг', 1, 1000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (7, 'Цибуля', 'кг', 1, 1000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (8, 'Сир пармезан', 'кг', 1, 50000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (9, 'Тісто для піци', '', 0, 1000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (11, 'Філе куряче', 'кг', 1, 8000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (12, 'Базилік', 'кг', 1, 500);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (13, 'Сир моцарелла', 'кг', 1, 15000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (14, 'Сирний соус', 'кг', 1, 4000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (15, 'Горох', 'кг', 1, 20000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (16, 'Вершки', 'л', 1, 12000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (17, 'Жаб''ячі лапки', '', 0, 3500);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (18, 'Яловичина', 'кг', 1, 15000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (19, 'Гусяча печінка', 'кг', 1, 30000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (20, 'Сметана', 'кг', 1, 7000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (21, 'Тісто для вареників', 'кг', 1, 2000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (22, 'Макарони', 'кг', 1, 3500);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (23, 'Рис', 'кг', 1, 2000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (24, 'Тісто для пончиків', 'кг', 1, 3000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (25, 'Цукор', 'кг', 1, 1800);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (26, 'Згущене молоко', 'кг', 1, 8000);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (27, 'Мука', 'кг', 1, 1200);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (28, 'Яйце', '', 0, 600);
INSERT INTO ingredients (id, title, unit, floating, price) VALUES (29, 'Орегано', 'кг', 1, 12000);